In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [34]:
df=pd.read_csv("churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [36]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [37]:
df=df[["SeniorCitizen", "tenure", "InternetService", "OnlineSecurity", "OnlineBackup",
 "DeviceProtection", "TechSupport", "Contract", "PaperlessBilling", 
 "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn"]]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SeniorCitizen     7043 non-null   int64
 1   tenure            7043 non-null   int64
 2   InternetService   7043 non-null   object
 3   OnlineSecurity    7043 non-null   object
 4   OnlineBackup      7043 non-null   object
 5   DeviceProtection  7043 non-null   object
 6   TechSupport       7043 non-null   object
 7   Contract          7043 non-null   object
 8   PaperlessBilling  7043 non-null   object
 9   PaymentMethod     7043 non-null   object
 10  MonthlyCharges    7043 non-null   float64
 11  TotalCharges      7043 non-null   object
 12  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(10)
memory usage: 715.4+ KB

In [38]:
df.head()

,SeniorCitizen,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,1,DSL,No,Yes,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,34,DSL,Yes,No,Yes,No,One year,No,Mailed check,56.95,1889.5,No
2,0,2,DSL,Yes,Yes,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,0,45,DSL,Yes,No,Yes,Yes,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,0,2,Fiber optic,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [39]:
for col in ["SeniorCitizen", "tenure", "InternetService", "OnlineSecurity", "OnlineBackup",
 "DeviceProtection", "TechSupport", "Contract", "PaperlessBilling", 
 "PaymentMethod", "MonthlyCharges", "TotalCharges", "Churn"]:
    print(f"Unique values in {col}:")
    print(df[col].unique())
    print()

Unique values in SeniorCitizen:
[0 1]

Unique values in tenure:
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]

Unique values in InternetService:
['DSL' 'Fiber optic' 'No']

Unique values in OnlineSecurity:
['No' 'Yes' 'No internet service']

Unique values in OnlineBackup:
['Yes' 'No' 'No internet service']

Unique values in DeviceProtection:
['No' 'Yes' 'No internet service']

Unique values in TechSupport:
['No' 'Yes' 'No internet service']

Unique values in Contract:
['Month-to-month' 'One year' 'Two year']

Unique values in PaperlessBilling:
['Yes' 'No']

Unique values in PaymentMethod:
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

Unique values in MonthlyCharges:
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]

Unique values in TotalCharges:
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']

Unique values in Churn:
['No' 'Yes']

In [40]:
Cat_col = ["InternetService","OnlineSecurity","OnlineBackup","DeviceProtection",
           "TechSupport","Contract","PaperlessBilling","PaymentMethod","Churn"]

for col in Cat_col:
    Encoder = LabelEncoder()  # create a new encoder for each column
    df[col] = Encoder.fit_transform(df[col])

In [41]:
df.head()

,SeniorCitizen,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,1,0,0,2,0,0,0,1,2,29.85,29.85,0
1,0,34,0,2,0,2,0,1,0,3,56.95,1889.5,0
2,0,2,0,2,2,0,0,0,1,3,53.85,108.15,1
3,0,45,0,2,0,2,2,1,0,0,42.30,1840.75,0
4,0,2,1,0,0,0,0,0,1,2,70.70,151.65,1

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SeniorCitizen     7043 non-null   int64
 1   tenure            7043 non-null   int64
 2   InternetService   7043 non-null   int32
 3   OnlineSecurity    7043 non-null   int32
 4   OnlineBackup      7043 non-null   int32
 5   DeviceProtection  7043 non-null   int32
 6   TechSupport       7043 non-null   int32
 7   Contract          7043 non-null   int32
 8   PaperlessBilling  7043 non-null   int32
 9   PaymentMethod     7043 non-null   int32
 10  MonthlyCharges    7043 non-null   float64
 11  TotalCharges      7043 non-null   object
 12  Churn             7043 non-null   int32
dtypes: float64(1), int32(9), int64(2), object(1)
memory usage: 467.8+ KB

In [51]:
df["TotalCharges"] = df["TotalCharges"].replace("", np.nan)
df["TotalCharges"] = df["TotalCharges"].astype(float)

In [54]:
Scal_col = ["tenure","MonthlyCharges","TotalCharges"]

for col in Scal_col:
    Scaler = StandardScaler()
    df[col] = Scaler.fit_transform(df[[col]])

In [55]:
df.head()

,SeniorCitizen,tenure,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,-1.277445,0,0,2,0,0,0,1,2,-1.160323,-0.994194,0
1,0,0.066327,0,2,0,2,0,1,0,3,-0.259629,-0.173740,0
2,0,-1.236724,0,2,2,0,0,0,1,3,-0.362660,-0.959649,1
3,0,0.514251,0,2,0,2,2,1,0,0,-0.746535,-0.195248,0
4,0,-1.236724,1,0,0,0,0,0,1,2,0.197365,-0.940457,1

In [56]:
X = df.drop("Churn",axis=1)
y = df["Churn"]

In [57]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [58]:
# Random Forest
RF = RandomForestClassifier(n_estimators=100, random_state=42)
RF.fit(X_train,y_train)

y_pred = RF.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy :  0.7927117841930904
Confusion Matrix:
 [[1396  143]
 [ 295  279]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.91      0.86      1539
           1       0.66      0.49      0.56       574

    accuracy                           0.79      2113
   macro avg       0.74      0.70      0.71      2113
weighted avg       0.78      0.79      0.78      2113

In [59]:
# XG_boost
XG_model = XGBClassifier()
XG_model.fit(X_train,y_train)

y_pred = XG_model.predict(X_test)
print("Accuracy : ",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy :  0.7884524372929484
Confusion Matrix:
 [[1380  159]
 [ 288  286]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.90      0.86      1539
           1       0.64      0.50      0.56       574

    accuracy                           0.79      2113
   macro avg       0.74      0.70      0.71      2113
weighted avg       0.78      0.79      0.78      2113